import { Epilogue } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { Metadata } from "next";
import "../globals.css";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
  };
  
export default function RootLayout({
	children,
}: {
  children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={epilogue.className}>
				<main>{children}</main>
				<Toaster />
			</body>
		</html>
	);
}
